"""add unique constraint on member group_id name

Revision ID: c2c71760ac8d
Revises: d85f1d0539cc
Create Date: 2026-09-12 09:10:00.459837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c71760ac8d'
down_revision: Union[str, None] = 'd85f1d0539cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_member_group_name', ['group_id', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_member_group_name', type_='unique')

    # ### end Alembic commands ###
